[colors.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#6ae3fa"
green = "#3bd01d"
magenta = "#ff55ff"
red = "#f40e17"
white = "#ffffff"
yellow = "#edc809"

[colors.cursor]
cursor = "#f0cc09"
text = "#fefff2"

[colors.normal]
black = "#000000"
blue = "#1460d2"
cyan = "#00bbbb"
green = "#38de21"
magenta = "#ff005d"
red = "#ff0000"
white = "#bbbbbb"
yellow = "#ffe50a"

[colors.primary]
background = "#132738"
foreground = "#ffffff"

[colors.selection]
background = "#18354f"
text = "#b5b5b5"

[font]
size = 12.5

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
opacity = 1

[window.position]
x = 0
y = 0
